Repository HBRS-MAAS/project, pull requests merged in 2019-01, with the labels that each got.

#100 BaseAgent changes for visualizer
  src/main/java/org/maas/agents/BaseAgent.java
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/maas/agents/LoadingBayAgent.java
  src/main/java/org/maas/objects/ProcessedProduct.java
Labels: integration

#103 Update cooling rack
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/maas/agents/LoadingBayAgent.java
Labels: integration

#92 Develop to master
  .gitignore
  .travis.yml
  docs/messages/customer.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/maas/BakingStageInitializer.java
  src/main/java/org/maas/CustomerInitializer.java
  src/main/java/org/maas/Initializer.java
  src/main/java/org/maas/Objects/Order.java
  src/main/java/org/maas/OrderProcessingInitializer.java
  src/main/java/org/maas/PackagingStageInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/BaseAgent.java
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/maas/agents/CustomerAgent.java
  src/main/java/org/maas/agents/LoadingBayAgent.java
  src/main/java/org/maas/agents/TimeKeeper.java
  src/main/java/org/maas/data/models/Bakery.java
  src/main/java/org/maas/data/models/Batch.java
  src/main/java/org/maas/data/models/DoughPrepTable.java
  src/main/java/org/maas/data/models/Equipment.java
  src/main/java/org/maas/data/models/KneadingMachine.java
  src/main/java/org/maas/data/models/Location.java
  src/main/java/org/maas/data/models/Oven.java
  src/main/java/org/maas/data/models/Packaging.java
  src/main/java/org/maas/data/models/Product.java
  src/main/java/org/maas/data/models/Recipe.java
  src/main/java/org/maas/data/models/Step.java
  src/main/java/org/maas/objects/ProcessedProduct.java
  src/main/java/org/maas/utils/Data.java
Labels: Needs review

#111 Added visualisation from right-brothers
  docs/visualizer/right_brothers/class-diagram.png
  docs/visualizer/right_brothers/class-diagram.ucls
  docs/visualizer/right_brothers/ui-architecture.pdf
  docs/visualizer/right_brothers/ui-architecture.tex
  docs/visualizer/right_brothers/visualizer-complete.png
  docs/visualizer/right_brothers/visualizer-ui.png
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/VisualizationAgent.java
  src/main/java/org/maas/data/messages/LoadingBayBox.java
  src/main/java/org/maas/data/messages/LoadingBayMessage.java
  src/main/java/org/maas/data/messages/UnbakedProductMessage.java
  src/main/java/org/maas/visualizer/model/BakingStageCard.java
  src/main/java/org/maas/visualizer/model/CardItem.java
  src/main/java/org/maas/visualizer/model/PackagingStageCard.java
  src/main/java/org/maas/visualizer/model/StageCard.java
  src/main/java/org/maas/visualizer/model/TimelineItem.java
  src/main/java/org/maas/visualizer/ui/BakingCardController.java
  src/main/java/org/maas/visualizer/ui/BakingStageController.java
  src/main/java/org/maas/visualizer/ui/DeliveryCardController.java
  src/main/java/org/maas/visualizer/ui/DeliveryStageController.java
  src/main/java/org/maas/visualizer/ui/LayoutController.java
  src/main/java/org/maas/visualizer/ui/PackagingCardController.java
  src/main/java/org/maas/visualizer/ui/PackagingStageController.java
  src/main/java/org/maas/visualizer/ui/ScenarioAware.java
  src/main/java/org/maas/visualizer/ui/StageController.java
  src/main/java/org/maas/visualizer/ui/Visualizer.java
  src/main/resources/fxml/right_brothers/BakingCard.fxml
  src/main/resources/fxml/right_brothers/BakingStage.fxml
  src/main/resources/fxml/right_brothers/DeliveryCard.fxml
  src/main/resources/fxml/right_brothers/DeliveryStage.fxml
  src/main/resources/fxml/right_brothers/Layout.fxml
  src/main/resources/fxml/right_brothers/LayoutTemplate.fxml
  src/main/resources/fxml/right_brothers/PackagingCard.fxml
  src/main/resources/fxml/right_brothers/PackagingStage.fxml
  src/main/resources/fxml/right_brothers/application.css
  src/main/resources/fxml/right_brothers/exit.png
  src/main/resources/fxml/right_brothers/logo.png
  src/main/resources/fxml/right_brothers/menu.png
  src/main/resources/fxml/right_brothers/replay.png
Labels: visualization

#116 Fixed start to run multiple machines and updated docs
  README.md
  docs/start.md
  src/main/java/org/maas/Start.java
Labels: bug, integration

#122 Removed customer prints
  .travis.yml
  src/main/java/org/maas/agents/CustomerAgent.java
Labels: enhancement, integration

#123 Develop to master
  .idea/gradle.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_annotations_2_9_0.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_core_2_9_3.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_databind_2_9_3.xml
  .idea/libraries/Gradle__com_google_code_gson_gson_2_7.xml
  .idea/libraries/Gradle__com_tilab_jade_jade_4_5_0.xml
  .idea/libraries/Gradle__commons_codec_commons_codec_1_3.xml
  .idea/libraries/Gradle__org_json_json_20180813.xml
  .idea/modules.xml
  .travis.yml
  README.md
  docs/messages/GraphVisualization.md
  docs/messages/customer.md
  docs/messages/order-processing.md
  docs/messages/proofer.md
  docs/messages/scheduler.md
  docs/start.md
  docs/visualizer/commitment_issues/VIsualizationDocument.pdf
  src/main/java/org/maas/JSONConverter.java
  src/main/java/org/maas/Objects/OrderMas.java
  src/main/java/org/maas/Objects/OvenSlot.java
  src/main/java/org/maas/Objects/Product.java
  src/main/java/org/maas/Objects/ProductStatus.java
  src/main/java/org/maas/Objects/WorkQueue.java
  src/main/java/org/maas/OrderProcessingInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/CustomerAgent.java
  src/main/java/org/maas/agents/MailboxAgent.java
  src/main/java/org/maas/agents/OrderProcessing.java
  src/main/java/org/maas/agents/Proofer.java
  src/main/java/org/maas/agents/SchedulerAgent.java
  src/main/java/org/maas/agents/TimeKeeper.java
  src/main/java/org/maas/behaviours/shutdown.java
  src/main/java/org/maas/messages/BakingRequest.java
  src/main/java/org/maas/messages/CoolingRequest.java
  src/main/java/org/maas/messages/PreparationNotification.java
  src/main/java/org/maas/utils/Logger.java
Labels: Needs review, integration
